-- MySQL Script generated by MySQL Workbench
-- Thu Mar  2 21:06:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `idAluno` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  PRIMARY KEY (`idAluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disciplinas` (
  `idDisciplina` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sigla` VARCHAR(5) NOT NULL,
  `semestre` INT NOT NULL,
  `aulas_total` INT NOT NULL,
  `aulas_semana` INT NOT NULL,
  `Curso_idCurso` INT NOT NULL,
  `Aluno_idAluno` INT NOT NULL,
  PRIMARY KEY (`idDisciplina`, `Aluno_idAluno`),
  INDEX `fk_Disciplinas_Aluno1_idx` (`Aluno_idAluno` ASC) VISIBLE,
  CONSTRAINT `fk_Disciplinas_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `mydb`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `idProfessor` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `sexo` VARCHAR(45) BINARY NOT NULL,
  `data_nascimento` DATE NULL,
  `email` VARCHAR(100) NULL,
  `telefone` INT NULL,
  `Disciplinas_idDisciplina` INT NOT NULL,
  PRIMARY KEY (`idProfessor`, `Disciplinas_idDisciplina`),
  INDEX `fk_Professor_Disciplinas1_idx` (`Disciplinas_idDisciplina` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_Disciplinas1`
    FOREIGN KEY (`Disciplinas_idDisciplina`)
    REFERENCES `mydb`.`Disciplinas` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `idCurso` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sigla` VARCHAR(5) NULL,
  `duracao` INT NOT NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turma` (
  `idTurma` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `codigo` CHAR(2) NOT NULL,
  `disciplina_id` INT NOT NULL,
  `Curso_idCurso` INT NOT NULL,
  `Aluno_idAluno` INT NOT NULL,
  PRIMARY KEY (`idTurma`, `Curso_idCurso`, `Aluno_idAluno`),
  INDEX `fk_Turma_Curso_idx` (`Curso_idCurso` ASC) VISIBLE,
  INDEX `fk_Turma_Aluno1_idx` (`Aluno_idAluno` ASC) VISIBLE,
  CONSTRAINT `fk_Turma_Curso`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `mydb`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `mydb`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turma_Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turma_Professor` (
  `Turma_idTurma` INT UNSIGNED NOT NULL,
  `Turma_Curso_idCurso` INT NOT NULL,
  `Turma_Aluno_idAluno` INT NOT NULL,
  `Professor_idProfessor` INT NOT NULL,
  PRIMARY KEY (`Turma_idTurma`, `Turma_Curso_idCurso`, `Turma_Aluno_idAluno`, `Professor_idProfessor`),
  INDEX `fk_Turma_has_Professor_Professor1_idx` (`Professor_idProfessor` ASC) VISIBLE,
  INDEX `fk_Turma_has_Professor_Turma1_idx` (`Turma_idTurma` ASC, `Turma_Curso_idCurso` ASC, `Turma_Aluno_idAluno` ASC) VISIBLE,
  CONSTRAINT `fk_Turma_has_Professor_Turma1`
    FOREIGN KEY (`Turma_idTurma` , `Turma_Curso_idCurso` , `Turma_Aluno_idAluno`)
    REFERENCES `mydb`.`Turma` (`idTurma` , `Curso_idCurso` , `Aluno_idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_has_Professor_Professor1`
    FOREIGN KEY (`Professor_idProfessor`)
    REFERENCES `mydb`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
